/** Built-in category packages for برا السالفة (Out of the Loop). */

/** @typedef {{ id: string, nameAr: string, nameEn: string, description: string, words: string[] }} CategoryPackage */

/** @type {CategoryPackage[]} */
export const CATEGORY_PACKAGES = [
  {
    id: "food",
    nameAr: "الأكلات والمشروبات",
    nameEn: "Food & Drinks",
    description: "أطباق يومية محلية وعالمية ومشروبات",
    words: [
      "شاورما",
      "دولمة",
      "منسف",
      "كشري",
      "كبسة",
      "فلافل",
      "شاي كرك",
      "برجر",
      "بيتزا",
      "كنافة",
      "حمص",
      "مندي",
      "مقلوبة",
      "فتوش",
      "عصير ليمون",
      "قهوة عربية",
      "سوشي",
      "تاكو",
      "باستا",
      "آيس كريم",
      "معكرونة",
      "بقلاوة",
      "مشاوي",
      "فطور",
      "عصير برتقال",
    ],
  },
  {
    id: "jobs",
    nameAr: "الوظائف والمهن",
    nameEn: "Jobs & Professions",
    description: "مهن ومسارات مهنية متنوعة",
    words: [
      "مبرمج",
      "طبيب",
      "سباك",
      "طيار",
      "صانع محتوى",
      "شرطي",
      "طباخ",
      "رائد فضاء",
      "معلم",
      "محامي",
      "مهندس",
      "ممرض",
      "مصور",
      "مزارع",
      "نجار",
      "خباز",
      "صيدلي",
      "مذيع",
      "مدرب رياضي",
      "مصمم أزياء",
      "عالم",
      "سائق تاكسي",
      "حلاق",
      "كاتب",
      "ميكانيكي",
    ],
  },
  {
    id: "places",
    nameAr: "أماكن ومعالم",
    nameEn: "Places & Landmarks",
    description: "بيئات شائعة ومعالم سياحية",
    words: [
      "مطار",
      "قاعة رياضية",
      "سينما",
      "المحطة",
      "مستشفى",
      "جامعة",
      "شاطئ",
      "الأهرامات",
      "مقهى",
      "سوق",
      "حديقة",
      "مكتبة",
      "فندق",
      "مسجد",
      "متحف",
      "برج إيفل",
      "ديزني لاند",
      "مول",
      "مطعم",
      "ملعب",
      "غابة",
      "جبل",
      "ميناء",
      "قصر",
      "حديقة حيوان",
    ],
  },
  {
    id: "popculture",
    nameAr: "ثقافة بوب ومشاهد",
    nameEn: "Pop Culture & Media",
    description: "شخصيات وأعمال مشهورة عالمياً وإقليمياً",
    words: [
      "ميسي",
      "رونالدو",
      "سبايدرمان",
      "باتمان",
      "المحقق كونان",
      "أنمي",
      "لعبة فيفا",
      "قراصنة الكاريبي",
      "هاري بوتر",
      "مارفل",
      "تيك توك",
      "يوتيوب",
      "نتفليكس",
      "ببجي",
      "ماينكرافت",
      "سوبر ماريو",
      "بيكاتشو",
      "ستار وورز",
      "أفاتار",
      "ذا روك",
      "كرة القدم",
      "أولمبياد",
      "أوسكار",
      "كيبوب",
      "فورمولا واحد",
    ],
  },
  {
    id: "household",
    nameAr: "أغراض ومقتنيات",
    nameEn: "Household Items",
    description: "أشياء يومية في المنزل والمكتب",
    words: [
      "غسالة",
      "ثلاجة",
      "ملعقة",
      "ريموت كنترول",
      "شاحن",
      "مفتاح",
      "مرآة",
      "ستائر",
      "مكنسة",
      "مروحة",
      "ساعة حائط",
      "وسادة",
      "بطانية",
      "مقص",
      "قلم",
      "دفتر",
      "حقيبة",
      "نظارة",
      "سماعات",
      "كوب",
      "طبق",
      "مقلاة",
      "مصباح",
      "سلة مهملات",
      "مكواة",
    ],
  },
];

export const CATEGORY_PACKAGE_IDS = CATEGORY_PACKAGES.map((p) => p.id);

/** @param {string} id */
export function getCategoryPackage(id) {
  return CATEGORY_PACKAGES.find((p) => p.id === id) ?? null;
}

/** @param {string[]} pool @param {number} count */
export function pickRandomWords(pool, count) {
  const copy = [...pool];
  const picked = [];
  while (picked.length < count && copy.length > 0) {
    const idx = Math.floor(Math.random() * copy.length);
    picked.push(copy.splice(idx, 1)[0]);
  }
  return picked;
}
